#!/bin/bash

if [ $# -eq 0 ] ; then
        echo "Please supply a disk path ala /dev/sdx" >&2
        exit 1
fi

TMPDIR=boo

validate-part()
{
        local Part=

        Part="$1"; shift
        [ -b "${Part}" ]  && return 0
        # [ -b "${Part:0: -1}" ]  && return 0
        echo "Not a partition $Part" >&2
        return 1
}

setup-disk()
{
        local Part=

        Part="$1"; shift
        CMD="cat sfdisk.txt | sudo sfdisk \"${Part%1}\""
        echo "$CMD"
        eval "$CMD"
}

setup-fs()
{
        local Part=

        Part="$1"; shift
        CMD="sudo mkfs -t ext4 $Part"
        echo "$CMD"
        eval "$CMD"
}

mnt-initial()
{
        local User=
        local Part=

        Part="$1" ; shift
        User="$1" ; shift
        sudo -H mkdir -p /home/$TMPDIR/
        # sudo -H chown $User:$User /home/$TMPDIR/
        sudo -H mount /dev/$Part /home/$TMPDIR/$User
        sudo -H chown -R $User:$User /home/$TMPDIR
}

dup-user()
{
        local User=

        User="$1"
        sudo rcp -rp /home/$User/. /home/$TMPDIR/
}

update-fstab()
{
        local User=
        local Part=

        [ $# -eq 2 ] || return 3

        User="$1"; shift
        Part="$1"; shift
        Uuid=$(lsblk --fs /dev/$Part | tail -1 | awk '{print $4}')
        eval "sudo sed -i -e '\$aUUID='$Uuid' /home/'$User'      ext4    errors=remount-ro 0       1' /etc/fstab"
}

DEVICE="$1"
echo "Validate $DEVICE"
if ! validate-part $DEVICE ; then exit 1 ; fi

echo "Setup disk $DEVICE"
if ! setup-disk $DEVICE ; then exit 2 ; fi

echo "Create filesystem on $1"
if ! setup-fs $DEVICE ; then exit 3 ; fi

echo "Mount $DEVICE to $TMPDIR"
if ! mnt-initial $USER $DEVICE ; then exit 3 ; fi

dup-user $USER
update-fstab $USER $

